name: Error test
on:
  push:
jobs:
  RepoError:
    name: RepoError
    runs-on: self-hosted
    steps:
      - name: Printenv
        run: printenv
      - name: Release
        run: nix-shell -p helo --run "echo hello"
